FROM registry.redhat.io/rhel8/go-toolset:1.12 AS builder
WORKDIR /root/origin-4.3
COPY . .
RUN make build WHAT=cmd/openshift-tests; \
    mkdir -p /tmp/build; \
    cp /root/origin-4.3/_output/local/bin/linux/$(go env GOARCH)/openshift-tests /tmp/build/openshift-tests

FROM registry.redhat.io/openshift4/ose-cli:v4.3
COPY --from=builder /tmp/build/openshift-tests /usr/bin/
RUN yum install --setopt=tsflags=nodocs -y git gzip util-linux && yum clean all && rm -rf /var/cache/yum/* && \
    git config --system user.name test && \
    git config --system user.email test@test.com && \
    chmod g+w /etc/passwd
LABEL io.k8s.display-name="OpenShift End-to-End Tests" \
      io.k8s.description="OpenShift is a platform for developing, building, and deploying containerized applications." \
      io.openshift.tags="openshift,tests,e2e"